language: node_js

sudo: required
services: docker

before_install:
  - docker build -t sitespeedio/browsertime .
  - docker build -f ./Dockerfile-test -t sitespeedio/browsertime-test .
  - docker run --rm sitespeedio/browsertime -V

script:
- docker run --rm sitespeedio/browsertime-test npm run lint
- docker run --rm sitespeedio/browsertime-test npm test

notifications:
  slack:
    secure: V71EkIzwOf/fZnGTGIKAIFlDyLUit4tK97VDgdV9vZ7CbvOXI1ir3lwRZ57lNqiYD8BUaX+/wKDG+LyrBMgQ4JAGgQx0mECvmOKx1+10Yg9FAkUsMTWe7GOxcVMwhpS2OfHnXwMb0FjcuVl8ovowIZqCWOLeEAYVaTWHndDm2cA=
